/**********************************************************************/
/*                                                                    */
/*                 Licensed Materials - Property of IBM               */
/*          © Copyright IBM Corp. 2000   All Rights Reserved          */
/*                                                                    */
/**********************************************************************/

/* The first VLIW instruction in a program is located at VLIW_INST_BASE_ADDR
   and the VLIW instructions in each file are aligned on a VLIW_INST_ALIGN
   boundary.  VLIW_INST_BASE_ADDR must match the value used in the assembly
   code generated by makeglue.c. 
*/
#define VLIW_INST_BASE_ADDR	0x10000000
#define VLIW_INST_ALIGN		1024

#define CURR_CNTS_MAGIC_NUM		0xfeedfeed

typedef struct {
   unsigned offset;
   unsigned num_ins;
   unsigned code_size;
   char	    basename[1];
} INS_OFFSET;

typedef struct {
   unsigned *num_cnts;
   unsigned *cnts;
   char	    *name;
} VLIW_CNTS;
